
# Spring boot application
spring:
  application:
    name: dubbo-provider-demo
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.feint.dubboserviceweb.rpc